name: videomme
video_dir: data/Video-MME/data
subtitle_dir: data/Video-MME/subtitle
annotation_path: data/Video-MME/videomme/test-00000-of-00001.parquet
duration_split: all   # all | short | medium | long

metrics:
  type: videomme_mcq
